# Generated by Django 3.0.7 on 2020-06-12 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_enabled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='enabled',
            new_name='published',
        ),
    ]
